#!/bin/sh

setbg & # Wallpaper script
xcompmgr & # Composite Manager
remaps & # Keymapping
statusbar & # Statusbar script
mpd & # Music Player Daemon
dunst & # Simple notification daemon
unclutter & # Remove mouse pointer when not moved
sxhkd & # Manage keyboard shortcuts
exec dwm
